### ISSUE TITLE
yarn start script throwing syntax error

### ISSUE THREAD

**Issue by natguy** [graphql-boilerplates/react-fullstack-graphql#151]
```
yarn start
yarn run v1.3.2
warning package.json: No license field
$ node src/index.js
etc etc.../my-app/server/src/index.js:55
    ...req,
    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
error Command failed with exit code 1.
```

and:

node -v
v8.1.4

via nvm:

which node
/Users/etc etc/.nvm/versions/node/v8.1.4/bin/node

Thanks.

**Comment by natguy** [comment]
Note: I installed node v9.4.0 and it seems to be a-ok.

**Comment by marktani** [comment]
Can confirm, a recent Node 8 version or 9 is required.
