### ISSUE TITLE
es6 support

### ISSUE THREAD

**Issue by gHashTag** [graphql-boilerplates/react-fullstack-graphql#413]
#### I tryed:
`yarn add -D babel-cli babel-plugin-transform-object-rest-spread babel-preset-env`

#### package.json
`"start": "nodemon -e js,graphql -x node -r dotenv/config babel-node src/index.js",`

#### .babelrc
```javascript
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "node": "6.10"
        }
      }
    ]
  ],
  "plugins": [
    [
      "transform-object-rest-spread",
      {
        "useBuiltIns": true
      }
    ]
  ]
}
```

#### but I get an error in response:

```
[nodemon] starting `node -r dotenv/config babel src/index.js`
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '/Users/xyz/iYOGi/prisma/server/babel'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

**Comment by Gomah** [comment]
From npm@5.2.0, npm ships with npx package which lets you run commands from a local node_modules/.bin or from a central cache.

Try:

```json
"start": "nodemon -e js,graphql -x node -r dotenv/config --exec npx babel-node src/index.js"
```

**Comment by brainafesoh** [comment]
Hi... got the same issue, any updates already?
